version: '3.8'

services:
  qdrant-db:
    build:
      context: ./docker
      dockerfile: Dockerfile.db

    volumes:
      - ./qdrant_storage:/qdrant/storage
    ports:
      - "6333:6333"
      - "6334:6334"

  # backend:
  #   # Replace this with your backend service setup
  #   image: your-backend-image
  #   depends_on:
  #     - qdrant
  #   ports:
  #     - "your-backend-port:your-backend-port"
  #   environment:
  #     - QDRANT_HOST=qdrant
  #     - QDRANT_PORT=6333
